name: controle_financeiro
description: Aplicação para controle financeiro pessoal
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  progress_dialog: ^1.2.3
  date_field: ^0.1.2
  dio: ^3.0.9
  rxdart: ^0.24.1
  bloc_pattern: ^2.5.1
  charts_flutter: ^0.9.0
  flutter:
    sdk: flutter


dev_dependencies:
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
